apiVersion: v1
kind: Service
metadata:
  name: stressme
  labels:
    app: stressme
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: stressme
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stressme
spec:
  selector:
    matchLabels:
      app: stressme # has to match .spec.template.metadata.labels
  serviceName: "stressme"
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: stressme # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: stressme
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "150m"
      initContainers:
      - name: init-www
        image: busybox
        command: ['sh', '-c', 'echo "Hello, World! $(cat /etc/hostname)" > /usr/share/nginx/html/index.html']
        volumeMounts:
        - name: stressme
          mountPath: /usr/share/nginx/html             
  volumeClaimTemplates:
  - metadata:
      name: stressme
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: stressme
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: stressme
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: stresser
  name: stresser
spec:
  containers:
  - image: busybox
    name: stresser
    command: ['sh', '-c', 'while true; do wget -q -O- http://stressme/; done']